print("Welcome to the PyPassword Generator")
letters = int(input("How many letters would you like in your password?"))
symbols = int(input("How many symbols would you like?"))
number = int(input("How many numbers would you like?"))
print("Here is your password: ", password)